import { useState } from 'react';
import { CallData } from './useCalls';

export function useTranscript() {
  const [selectedTranscript, setSelectedTranscript] = useState<CallData | null>(null);
  const [isTranscriptOpen, setIsTranscriptOpen] = useState(false);

  const handleViewTranscript = (call: CallData) => {
    setSelectedTranscript(call);
    setIsTranscriptOpen(true);
  };

  const handleCloseTranscript = () => {
    setIsTranscriptOpen(false);
    setSelectedTranscript(null);
  };

  const handleDownloadReport = (call: CallData) => {
    if (!call) return;

    const reportContent = `
CALL REPORT - ${call.title}
${new Date(call.date).toLocaleString()} • ${call.duration}
Generated on: ${new Date().toLocaleString()}

==============================================

CALL SUMMARY:
${call.summary}

==============================================

FULL TRANSCRIPT:

${
  Array.isArray(call.transcript)
    ? call.transcript.map((entry) => `[${entry.time}] ${entry.speaker}: ${entry.text}`).join('\n')
    : 'No transcript available'
}

==============================================

CALL STATISTICS:
- Duration: ${call.duration}
- Total Exchanges: ${Array.isArray(call.transcript) ? call.transcript.length : 0}
- Resolution Status: Completed Successfully
- Follow-up Required: No

==============================================

This report was generated by Persa AI Voice Assistant
© 2025 Persa AI - All rights reserved
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${call.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_report_${
      new Date().toISOString().split('T')[0]
    }.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  return {
    selectedTranscript,
    isTranscriptOpen,
    handleViewTranscript,
    handleCloseTranscript,
    handleDownloadReport,
  };
}
